<%@ Page Title="" Language="C#" MasterPageFile="~/appMaster/TSIDMain.Master" AutoEventWireup="false" 
   Inherits="System.Web.UI.Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphMainContent" runat="server">
<h2>Irrigation Development in Central Oregon</h2>
<p>From a report prepared by Scott E. Stuemke, MS, RPA for the District:</p>
<p>"Euro-American emigrants began settling the Upper Deschutes Basin when land grants became more difficult to acquire west of the Cascades under the Homestead Act of 1862. The Federal land grants acts encourage settlement in the late 1800s and early 1900s. The High Lava Plains lies in the rain shadow of the Cascades limiting the annual average precipitation to about 13 inches per year. It was realized that irrigation was needed in order to successfully farm the region.<p>
Small-scale irrigation projects were generally created through cooperative efforts involving local settlers and homesteaders who live adjacent or near a perennial reliable water sources. Little or no capital investment and minimal engineering technology characterize these cooperative projects. The other type of irrigation projects developed in Central Oregon were large scale projects and developed with large sums of capital investment.</p>
<p>The passage of the Carey Act in 1894 by the United State Congress further encouraged settlement of the western United States. This Act ceded millions of acres of land in ten states for the purpose of settlement if the landowner would settle, irrigate and cultivate their land patent. Settlers received 160 acres of land if they lived on it and within ten years converted at least twenty acres to irrigated agriculture.</p>
<p>The state of Oregon adopted the provisions of the Carey Act in 1901. This enabled legislation to create the State Land Board that administered reclamation and settlement of the arid lands east of the Cascades without the State assuming any cost liability. The State also allotted and controlled water and water rights."</p>

<h2>Squaw Creek Irrigation Company</h2>
<p>Squaw Creek Irrigation Company (SCIC) was first incorporated with the State of Oregon on <a href="PDF/SCIC1891ArticlesofIncorporation.pdf" target="_blank">February 21, 1891</a> in Crook County, Oregon.  (At that time Crook County included both Deschutes and Jefferson Counties.)  SCIC was formed to construct ditches, canals and flumes for general irrigation purposes.  To obtain its water supply, the corporation appropriated and diverted water from Squaw Creek, a tributary of the Deschutes River.</p>
<p>For administrative purposess, SCIC re-filed <a href="PDF/SCIC1895ArticlesofIncorporation.pdf" target="_blank">Articles of Incorporation</a> on November 11, 1895 as well as a <a href="PDF/SCICNoticetoDivertWater.pdf" target="">Notice of Intention</a> to divert water. Supplementary Articles of Incorporation, dated April 9, 1904, increased the capital stock to $10,000, divided into 200 shares with a par value of $50 each, and by resolution of the stockholders of March 7, 1914, certified by the Secretary of the corporation on May 18, 1914, and certified by the Commissioner of Corporations on July 20, 1914, the capital stock was increased to $37,400.</p>

<h3>Developing Infrastructure</h3>
<p>On May 29, 1897, Knox Huston completed his survey of the SCIC ditches. The <a href="PDF/SCIC1897CanalFieldNotes.pdf" target="_blank">Field Notes</a> for original Main Canal were filed at the Crook County Court on June 5, 1897. </p>
<p>The original SCIC main canal took approximately 16 years to cut through the rock and enlarge sufficiently to carry the water required by the water rights.  The early settlers had little to work with.  They had mules and a plow or a homemade V ditcher.  One of the most effective tools was the water itself.  During the winter the ditch rider would ride the ditch with an ax and chop off the roots of the juniper trees.  During the irrigation season the water would expose more of the roots and eventually the tree could be pulled out of the ditch.  Progress was slow but each year the ditch could hold a little more water.</p>
<p>In 1903, due to heavy snow packs in the late 1800s, farmers and ranchers whose water rights were supplied by Squaw Creek decided there was plenty of water for additional appropriations. In 1905 SCIC filed <a href="PDF/SCICCareyActApplication1905.pdf" target="_blank">this application</a> with the State Land Board and the U.S Department of the Interior under the <a href="http://en.wikipedia.org/wiki/Carey_Act" target="_blank">Carey Act</a> for the reclamation of 11,000 acres of land to be granted by the federal government to indivduals who would reclaim the land through irrigation. SCIC hired a surveyor to create a desert land selection under the Carey Act. The surveyor filed <a href="PDF/SCICCareyActCanalSurvey1905.pdf" target="_blank">this survey</a> that mapped the existing main canal from Squaw Creek to Lower Bridge as well as a new east branch.</p>

<h3>Oregon Water Law</h3>
<p>Oregon State water law was created in 1909.  The new law required that all existing water rights would be recognized and protected by a court process called "adjudication". Adjudicated rights are rights that were fully vested before the state began issuing permits and certificates under the new law.  In March of 1909 a proceeding was initiated before the Board of Control (now the State Water Board) for the purpose of determining the relative rights of the various claims to the waters of Squaw Creek. SCIC appeared in that proceeding and filed a statement of claims to the use those waters and submitted proof in support of those claims.  The 1909 Squaw Creek water rights adjudication was a complex process.  Over 100 contested cases were heard in the matter.</p>
<p>The first <a href="PDF/1911SquawCreekAdjudicationDecree.pdf" target="_blank">Adjudication Decree</a> was issued by the Circuit Court of the State of Oregon in Crook County on May 1, 1911. and the SCIC water rights were declared to perfected based on beneficial use.  On September 19, 1914, <a href="PDF/1914SquawCreekAdjudicationDecree.pdf" target="_blank">a second decree</a> was issued with supplemental findings to the original decree. These adjudications gave diverters from Squaw Creek (inside and outside SCIC) the ability to divert over 8000 acres of junior water rights.</p>
<p>On February 19, 1913 the local land office at The Dalles of the Department of the Interior requested a report on the progess of the desert land selection. In July of 1913, Special Agent W. B. Burt of the General Land Office (GLO) of the Department of the Interior was assigned to investigate and report.</p>

<h2>Squaw Creek Irrigation District</h2>
<p>In 1915 the Oregon State Legislature passed a law allowing for the formation of irrigation districts (local municipal government entities) from existing irrigation corporations.  Some of the advantages of becoming a quasi-municipality were to establish district boundaries, issue bonds and levy assessments through the county taxing authority. The law required 50 petitioners from the existing corporation. That same year 53 water users from SCIC applied for the formation of a district under that law.  Squaw Creek Irrigation District (SCID) was organized March 15, 1916 from the irrigation works and water rights of the Squaw Creek Irrigation Company.  In the <a href="PDF/1916OrderCreatingSCID.pdf" target="_blank">Order of Organization</a> granted by the Crook County court, a preliminarty irrigation district boundary was defined.  That boundary was revised by the court in 1918 to exclude properties that had objected to being included.</p>
<p>On October 28, 1915 Special Agent Burt submitted his <a href="PDF/SpecialAgentBurt1915Report.pdf" target="_blank">Engineering Report</a> and the <a href="1915MapofSCID.jpg" target="_blank">Map of Squaw Creek Irrigation District</a>.  In that report Special Agent Burt did a very thorough examination of water availability and came to the conclusion that water would not be available for priorities subsequent to 1895.</p>
<p>On March 4, 1918 the first meeting of the SCID Board of Directors (George F. Cyrus, Gus E. Stadig, and John W. Gotter) took place.</p>
<p>In 1923 H.H. deArmond was SCID's attorney and secretary.  SCID's records were kept in his office in downtown Sisters.On May 11 a fire broke out in Sisters and 10 buildings were destroyed. <a href="http://www.sisterscountryhistoricalsociety.org/Timeline.htm">(Sisters Country Historical Society Timeline)</a> One of these buildings was deArmond's office.  All the district's records were lost.</p>
<p>On April 21, 1924 Special Agent Burt filed <a href="PDF/SpecialAgentBurt1924Report.pdf" target="_blank">another report</a> in which he presented a complete legal and physical description of all the irrigation works and water rights of SCID. He concluded that SCID was legally organized, the irrigation works were satisfactory, the water rights had good title.  He also recommended that no approval be given to applications for desert land grants be given to entrymen with adjudicated water rights later than 1895.  Apparently no one paid attention to Special Agent Burt prior to 1924, because a number of entrymen successfully patented land grants under the 1877 Desert Land Act between 1908 and 1924.</p>
</asp:Content>
