<%@ Page Title="TSID History - The Middle Years" Language="C#" MasterPageFile="~/appMaster/TSIDMain.Master" 
    AutoEventWireup="false" Inherits="System.Web.UI.Page"%>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphMainContent" runat="server">
<h2>SCID Grows</h2>
<p>The Board of Directors deemed it  "necesary for the interests of the District that it acquire all the rights of the Squaw Creek Irrigation Company to the Squaw Creek irrigation system, including water rights, ditches, canals, and other lands." One of the stockholders in SCIC, Mr. Wurzweiler, refused to sell his interest in the delivery system without also selling what is known as Long Hollow Ranch.  So on March 25, 1918 the Board held a special meeting to call a special election to issue a bond in the amount of $125,000 to purchase the Black Butte Land & Livestock Company, their property (Long Hollow Ranch) with its apurtenant water rights, and their interest in the SCID irrigation system.  At the next regular board meeting on <a href="PDF/1918.04.02 Minutes.pdf">April 2, 1918</a> they took action and on May 4 1918, 26 electors voted (23 for, 3 against) and the district concluded the purchase.</p>
<p>In 1919 the annual assessment was $.19 per acre for 1895 acreage and $.26 per acre for junior acreage and $.15 per acre foot delivered.</p>

<h2>Diversion Dams Through the Years</h2>
<p>On May 3, 1919, the district held a special election to bond $15,000 for the district improvements, mainly a new dam to be constructed 6100 feet below the existing diversion on Squaw Creek. The re-location of the new dam conserved considerable ditch loss which had occurred through more than a mile of cobble leading from the old diversion.  In 1919, they built a concrete dam.  This dam washed out in the 1921 high water event.  In February of 1922 SCID bonded another $25,000 to build a log structure just below the washed out concrete structure.</p>
<p>From a report prepared by Scott E. Stuemke, MS, RPA for the District:</p>
<p>"The main canal was enlarged in 1912 and 1913 to extend the system to the upper end of Lower Bridge. All the work was done by hand and horse-drawn equipment. Progress continued on the system and the SCIC became the Squaw Creek Irrigation District (SCID) in 1917. It was the second district to formally file and be recognized by the State. The headworks was reconstructed in 1915 or 1916 and consisted of a concrete dam and concrete head works about a mile downstream. A new point of diversion was selected in 1919 and a new dam and headgate were built of concrete. The concrete diversion dam was improperly constructed and washed out and destroyed almost immediately during a flood event in 1920.</p>
<p>A log crib dam was built to replace the destroyed concrete structure. R.H. Bayley built this structure about forty feet below the original dam. The log crib dam was constructed by excavating the ground to hardpan including the removal of approximately six feet of gravel being removed. Logs were then “cribbed” in the bed of the stream with the cribs extending about twenty feet into the bank of both sides of the stream. This crib was carried about eight feet above the original bend of the stream. Twelve by twelve timbers were then laid against the upstream side of the crib at a forty-five degree angle with the lower end embedded in the hardpan. A mat of fir brush was laid to a depth of about one foot from fifteen feet upstream and on the timbers angled at forty-five degrees. The brush was then loaded with earth and gravel. The shore cribs were planked on the side toward the stream.</p>
<p>The spillway was about twenty-five feet long including a waste gate and extended the full width of the creek channel. The spillway portion of the dam was covered on top with four by twelve planks and similar planks placed at an angle of forty-five degrees covering the downstream face of the dam. Water running over the spillway fell on a floor of similar planks extending twelve feet down-stream.</p>
<p>A waste gate of five feet wide was cut in the west end of the dam with its bottom some four feet below the crest of the spillway. The gate operated against twelve by twelve timbers set vertically and dovetailed into the logs of the dam. Each timber was strongly braced on both the upstream and downstream side. The bottom of the gate was floored and the sides were planked. A gate made of plank and designed to work vertically in grooves made by leaving a space between the ends of planks in the sidewalls of the gate.</p>
<p>Logs were laid parallel to the bank from the dam up to the concrete gate on the west bank of the stream provided or the individual user. These logs were planked over to a level about four feet above the top of the spillway. The crib extended upstream about forty feet on the east bank of the stream and ran back of the concrete headgate to the district’s canal. The crib was filled with earth and not planked over.</p>
<p>The main canal ditch was rip-rapped with rock for about fifty feet below the headgate. The ditch was built through good soil and was not subject to excessive losses. The ditch was about twenty feet wide on the bottom and carried approximately four feet of water safely. It was designed to carry about 150 cubic feet per second (cfs) and has a recorded discharge of 155 cfs. The headworks are located in T15S, R10E, 5
Section 21 NW/SW. The ditch runs generally is an easterly direction for about a mile joining an older portion of the ditch near the west line of Section 22.</p>
<p>About 500 feet below the intake there is a waste gate in the lower bank of the ditch. The gate is set well below the grade of the ditch. It is about sixteen feet wide and built of concrete. A concrete wall extends about six feet into the lower bank of the ditch on the upstream side and another extends about three feet along the bank of the ditch on the downstream side. Concrete walls also extended about six feet down the banks of the waste ditch. The gate was closed by flashboards. Water is wasted down a draw to Squaw Creek.</p>
<p>Immediately below the waste gate there was a wheel installed by the State Fish Commission designed to turn with the current in the ditch and scare the fish from going down it. The wheel was considered to obstruct a portion of the ditch flow. An automatic discharge gate was located just below the wheel and probably installed by the Geological Survey."</p>

<p>The log dam did fairly well over the years.  By 1955 the District realized that it would have to be replaced at some point and designed a new dam to be installed upstream from the existing log crib structure.  It is not clear exactly what stopped them from installing the new dam for 15 years.  The log crib structure survived the 1964 Christmas Day flood.  The dam that heads the diversion today was installed in 1970.  In 2010 the District replaced the head gates with new stainless steel structures that can now be controlled using Supervisory Control and Data Acquistion (SCADA) and Telemetry.  Then in 2012 the wing walls on each side of the diversion were heightened and reinforced.</p>

<h2>Cloverdale Irrigation Company</h2>
<p>Rather than maintain their own diversion, the Cloverdale Irrigation Company water users contracted with SCID to have their water delivered through the SCID diversion and sent to the Cloverdale ditch at the Fryrear ditch split.  In 1926 the Cloverdale Irrigation Company dissolved (having gone out of business in 1923).  SCID absorbed its lands and irrigation works and proceeded to enlarge the Cloverdale canal between 1936 and 1940.  By 1940 SCID had enlarged the ditch sufficiently to connect to and better serve the users on the Smith ditch.</p>
<p>Two Cloverdale water users, Skelton with 1887 rights and Thompson with 1885 rights, had neither included in the District nor contracted with SCID for delivery of their water.  After many years of dicussion, an agreement was drafted and signed by SCID and Skelton in 1940.  This agreement became a bone of contention for the next 60 years.</p>

<h2>Making the Water Supply More Reliable</h2>
<p>In 1954 SCID approached the Mid State Soil and Water Conservation District (MSWCD) and the Agricultural Soil Conservation Service (ASCS) to design a regulating reservoir above the head works of the Black Butte and Association Canals which served the McKenzie Canyon and Lower Bridge users.  In 1957 SCID hired Jack Robinson & Sons to build the 12 acre McKenzie Reservoir which allowed for more consistent deliveries to the lower district.</p>
<p>In 1964 SCID purchased a 160 acre property from Charles and Vera Watson and again sought assistance from MSWCD & ASCS to design an 80 acre regulating reservoir.  That same year they built Watson Reservoir with a supplemental 500 acre foot storage right.  This allowed the district to keep a 5 to 7 day supply of water in reserve.</p>
<p>After the drought of 1977 the district applied for supplemental ground water well rights for the majority of irrigated acres in the district.  In 1978 SCID installed two pumps (150hp and 350hp) which gave the district the ability to pump up to 13 cfs of supplemental ground water into the canal when the primary creek water was in short supply.</p>
</asp:Content>
