<%@ Page Title="TSID History - Turning the Century" Language="C#"  MasterPageFile="~/appMaster/TSIDMain.Master" 
AutoEventWireup="false" Inherits="System.Web.UI.Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphMainContent" runat="server">
<%--<h2>TSID Grows Up</h2>--%>
<h3>New Names for All</h3>
<p>In 2001 the Oregon Legislature unanimously passed a law making it illegal to use the word "Squaw" in a name.  SCID started started contemplating what its new name should be.  That same year the US Forest Service and the Oceanagraphic Names Board started consultation with the Confederated Tribes of Warm Springs on changing the name of Squaw Creek.  At the June 2005 meeting of the Board of Directors, the District changed its name to Three Sisters Irrigation District.  Then in 2006 the name Squaw Creek was changed to Whychus Creek.  Whychus means "a place to cross".</p>

<h3>The Challenge of Fish</h3>
<p>In the late 1980s and early 1990s Three Sisters Irrigation District awoke to the reality that life was changing.  For over 100 years TSID had dried up Whychus Creek going through Sisters in the late summer months.  The district's delivery system of open canals lost upwards of 50% of the diverted flow to seepage and evapo-transpiration.  After suffering the drought of 1977 and the mulitple drought years in the early 1990s, TSID's farmers realized that conservation might be the key to avoiding future conflict as well as delivering more water to its farms.  The District started with smaller projects to prove viability of a model.  Starting in 1998, in partnership with the Natural Resources Conservation Service and the TSID farmers, the District set about piping 11 private laterals.</p>
<p>In 2005 the Lower Bridge farmers started work on the 5-year project to pipe <a href="/siteProjects/PJ-McKenzie.aspx">McKenzie Canyon Black Butte and Association</a> ditches.  This project firmed up a model that put half of the conserved water in Whychus Creek as protected flow in exchange for funding assistance with the project.</p>
<p>The FERC relicensing of the Round Butte-Pelton dam complex in 2006 came with a new set of challenges and opportunities.  One of the major components of the relicensing agreement was restoring anadromous fish populations above the dams in the Upper Deschutes.  Along with PGE and the Tribes, the anadromous re-introduction has been joined by numerous federal, state, local and non-profit entities in the Pacific NW.  In 2007, the various partners started planting fry for the species that historically spawned in Whychus Creek. </p>
<p>Bull Trout had been listed as threatened in 1999 throughout their historic range which includes Whychus Creek as well as the Mid-Coumbia summer Steelhead.  On August 14, 2007 Judge Michael Hogan of the US District Court in Oregon issued a decision that if a wild species was listed as endangered or threatened, then its hatchery-raised members are entitled to the same protection as the wild members.  Overnight the abundant Round Butte Hatchery strain of Steelhead became listed as threatened under the ESA.</p>
<p>Now the steelhead being placed in Whychus Creek and the Deschutes and Crooked Rivers are protected under the Endangered Species Act and harming them or their habitat (referred to as a "taking" by the ESA) results in stiff financial penalty.  This changes the landscape and the rules.  The District could no longer dry up the creek when the fry that had been planted above the diversion would be returning to spawn.  TSID's Board of Directors and farmers decided to take a more aggressive and proactive position in relation to conservation and improving Whychus in-stream flow and fish habitat.</p>
<p>The success of the McKenzie Canyon project and the pressure of the Anadromous Re-introduction moved the District to join with a number of partners in 2009 to pipe the <a href="/siteProjects/PJ-MainCanal.aspx">Main Canal</a> from diversion to Watson Reservoir, participate in a project to restore the creek at the diversion and 1400 feet downstream, and install a state of the art fish screen.  As of 2011, 34 miles of the 60 miles of canals and ditches have been piped.  These projects have resulted in over 20 cfs of permanently protected in-stream flow to Whychus Creek.  TSID farmers now receive up to 25% more water on their farms during short water periods.  Operations, maintenance and safety have all been improved and costs have been reduced.</p>

<h3>The Challenge of an Historic Irrigation System</h3>
<p>When the farmers started digging ditches in the high desert in the late 1800s, no one could have guessed that their irrigation delivery system would one day be considered historic.  With the additional challenges presented by the Clean Water Act and the Endangered Species Act, irrigation districts must adapt to a changing world.  As canals, ditches and diversion works are upgraded with new technology, the historic integrity of the system is degraded.  Piping to conserve water and improve in-stream flows eliminates the historic ditches dug by mule and scraper over 100 years ago.  Historic wooden lifts are replaced by far more practical and durable concrete.  To mitigate these affects on the historic irrigation artifacts of Central Oregon, TSID has been researching the history of the district for over a decade.  We have dedicated a portion of this website to share our historic compilation of information, documents and photos with the public.</p>
</asp:Content>